# <center> Text Generation - Next Word Prediction

## 1. Functions for Processing Text

### a. Reading in files as a string text

In [150]:
def read_file(filepath):

    with open(filepath) as f:
        str_text = f.read()

    return str_text

In [151]:
len("rahul")

5

In [152]:
len(read_file('whale2.txt'))

1215236

In [153]:
print(read_file('whale2.txt')[:5000])


ETYMOLOGY.

(Supplied by a Late Consumptive Usher to a Grammar School)

The pale Usher--threadbare in coat, heart, body, and brain; I see him now. He was ever dusting his old lexicons and grammars, with a queer handkerchief, mockingly embellished with all the gay flags of all the known nations of the world. He loved to dust his old grammars; it somehow mildly reminded him of his mortality.

"While you take in hand to school others, and to teach them by what name a whale-fish is to be called in our tongue leaving out, through ignorance, the letter H, which almost alone maketh the signification of the word, you deliver that which is not true." --HACKLUYT

"WHALE.... Sw. and Dan. HVAL. This animal is named from roundness or rolling; for in Dan. HVALT is arched or vaulted." --WEBSTER'S DICTIONARY

"WHALE.... It is more immediately from the Dut. and Ger. WALLEN; A.S. WALW-IAN, to roll, to wallow." --RICHARDSON'S DICTIONARY

     KETOS,               GREEK.
     CETUS,               LATIN.


### b. Tokenize and Clean Text

In [154]:
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
nlp.max_length = 1198623

In [155]:
def read_file(filepath):

    with open(filepath) as f:
        str_text = f.read()

    return str_text[:250000]

In [156]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [157]:
d = read_file('whale2.txt')
tokens = separate_punc(d)

In [158]:
type(tokens)

list

In [159]:
len(tokens)

45455

In [160]:
tokens[:10]

['etymology',
 'supplied',
 'by',
 'a',
 'late',
 'consumptive',
 'usher',
 'to',
 'a',
 'grammar']

### c. Create Sequences of Tokens

In [161]:
# organize into sequences of tokens
train_len = 25+1 # 25 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):

    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]

    # Add to list of sequences
    text_sequences.append(seq)

In [162]:
print(read_file('whale2.txt')[:1000])


ETYMOLOGY.

(Supplied by a Late Consumptive Usher to a Grammar School)

The pale Usher--threadbare in coat, heart, body, and brain; I see him now. He was ever dusting his old lexicons and grammars, with a queer handkerchief, mockingly embellished with all the gay flags of all the known nations of the world. He loved to dust his old grammars; it somehow mildly reminded him of his mortality.

"While you take in hand to school others, and to teach them by what name a whale-fish is to be called in our tongue leaving out, through ignorance, the letter H, which almost alone maketh the signification of the word, you deliver that which is not true." --HACKLUYT

"WHALE.... Sw. and Dan. HVAL. This animal is named from roundness or rolling; for in Dan. HVALT is arched or vaulted." --WEBSTER'S DICTIONARY

"WHALE.... It is more immediately from the Dut. and Ger. WALLEN; A.S. WALW-IAN, to roll, to wallow." --RICHARDSON'S DICTIONARY

     KETOS,               GREEK.
     CETUS,               LATIN.


In [163]:
' '.join(text_sequences[0])

'etymology supplied by a late consumptive usher to a grammar school the pale usher threadbare in coat heart body and brain i see him now he'

In [164]:
' '.join(text_sequences[1])

'supplied by a late consumptive usher to a grammar school the pale usher threadbare in coat heart body and brain i see him now he was'

In [165]:
' '.join(text_sequences[2])

'by a late consumptive usher to a grammar school the pale usher threadbare in coat heart body and brain i see him now he was ever'

In [166]:
len(text_sequences) #Every sentence is containing 26 words

45429

In [167]:
len(tokens) # These are total number of words in the whole novel

45455

In [168]:
print(len(text_sequences[0]))
print(text_sequences[0])

26
['etymology', 'supplied', 'by', 'a', 'late', 'consumptive', 'usher', 'to', 'a', 'grammar', 'school', 'the', 'pale', 'usher', 'threadbare', 'in', 'coat', 'heart', 'body', 'and', 'brain', 'i', 'see', 'him', 'now', 'he']


### d. Keras Tokenization

In [169]:
from keras.preprocessing.text import Tokenizer

In [170]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [171]:
print(len(sequences[0]))
print(sequences[0])

26
[7162, 1346, 30, 4, 476, 7161, 7157, 5, 4, 7160, 1893, 1, 1892, 7157, 7158, 6, 475, 276, 513, 2, 1891, 7, 91, 22, 39, 10]


In [172]:
type(tokenizer.index_word)

dict

In [173]:
' '.join(text_sequences[0])

'etymology supplied by a late consumptive usher to a grammar school the pale usher threadbare in coat heart body and brain i see him now he'

In [174]:
i=0
for a in tokenizer.index_word:
    print(a,"--->",tokenizer.index_word[a])
    i+=1
    if i==20 : break

1 ---> the
2 ---> and
3 ---> of
4 ---> a
5 ---> to
6 ---> in
7 ---> i
8 ---> that
9 ---> his
10 ---> he
11 ---> it
12 ---> was
13 ---> but
14 ---> with
15 ---> 's
16 ---> for
17 ---> all
18 ---> as
19 ---> at
20 ---> is


In [175]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

7162 : etymology
1346 : supplied
30 : by
4 : a
476 : late
7161 : consumptive
7157 : usher
5 : to
4 : a
7160 : grammar
1893 : school
1 : the
1892 : pale
7157 : usher
7158 : threadbare
6 : in
475 : coat
276 : heart
513 : body
2 : and
1891 : brain
7 : i
91 : see
22 : him
39 : now
10 : he


In [176]:
i=0
for a in tokenizer.word_counts:
    print((a,tokenizer.word_counts[a]))
    i+=1
    if i==10 : break

('etymology', 1)
('supplied', 80)
('by', 4917)
('a', 31636)
('late', 265)
('consumptive', 6)
('usher', 21)
('to', 27072)
('grammar', 10)
('school', 63)


In [177]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

7162

In [178]:
i=6990
for a in range(i,7000):
    print(a,"--->",tokenizer.index_word[a])
    #i+=1
    #if i==6999 : break

6990 ---> facts
6991 ---> triumphantly
6992 ---> cleanliest
6993 ---> tidy
6994 ---> granting
6995 ---> slippery
6996 ---> comparable
6997 ---> carrion
6998 ---> soldiers
6999 ---> plaudits


In [179]:
# tokenizer.index_word

### e. Convert to Numpy Matrix

In [180]:
import numpy as np

In [181]:
len(sequences)

45429

In [182]:
len(sequences[0])

26

In [183]:
sequences = np.array(sequences)

In [184]:
sequences.shape

(45429, 26)

In [185]:
sequences

array([[7162, 1346,   30, ...,   22,   39,   10],
       [1346,   30,    4, ...,   39,   10,   12],
       [  30,    4,  476, ...,   10,   12,  133],
       ...,
       [   1,  373, 7156, ...,  108,   27,    1],
       [ 373, 7156,  643, ...,   27,    1, 3012],
       [7156,  643,    5, ...,    1, 3012,  477]])

## 2. Creating an LSTM based model

In [186]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [187]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    model.summary()

    return model

## 3. Train / Test Split

In [188]:
from tensorflow.keras.utils import to_categorical

In [189]:
print(sequences.shape)
sequences

(45429, 26)


array([[7162, 1346,   30, ...,   22,   39,   10],
       [1346,   30,    4, ...,   39,   10,   12],
       [  30,    4,  476, ...,   10,   12,  133],
       ...,
       [   1,  373, 7156, ...,  108,   27,    1],
       [ 373, 7156,  643, ...,   27,    1, 3012],
       [7156,  643,    5, ...,    1, 3012,  477]])

In [190]:
# First 25 words
print(sequences[:,:-1].shape)
sequences[:,:-1]

(45429, 25)


array([[7162, 1346,   30, ...,   91,   22,   39],
       [1346,   30,    4, ...,   22,   39,   10],
       [  30,    4,  476, ...,   39,   10,   12],
       ...,
       [   1,  373, 7156, ...,    1,  108,   27],
       [ 373, 7156,  643, ...,  108,   27,    1],
       [7156,  643,    5, ...,   27,    1, 3012]])

In [191]:
# last Word
print(sequences[:,-1].shape)
sequences[:,-1]

(45429,)


array([  10,   12,  133, ...,    1, 3012,  477])

In [192]:
X = sequences[:,:-1]

In [193]:
X.shape

(45429, 25)

In [194]:
y = sequences[:,-1]

In [195]:
y.shape

(45429,)

In [196]:
y = to_categorical(y, num_classes=vocabulary_size)

In [197]:
y.shape

(45429, 7162)

In [198]:
seq_len = X.shape[1]

In [199]:
seq_len

25

## 4. Training the Model

In [200]:
# define model
model = create_model(vocabulary_size, seq_len)
#model = create_model(vocabulary_size, seq_len)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 25, 25)            179050    
                                                                 
 lstm_4 (LSTM)               (None, 25, 150)           105600    
                                                                 
 lstm_5 (LSTM)               (None, 150)               180600    
                                                                 
 dense_4 (Dense)             (None, 150)               22650     
                                                                 
 dense_5 (Dense)             (None, 7162)              1081462   
                                                                 
Total params: 1569362 (5.99 MB)
Trainable params: 1569362 (5.99 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


---

----

## 5. Fit model

In [201]:
history = model.fit(X, y, batch_size=512, epochs=250,verbose=1,validation_batch_size=.20)

Epoch 1/250
89/89 [==============================] - 17s 146ms/step - loss: 7.2786 - accuracy: 0.0483
Epoch 2/250
89/89 [==============================] - 8s 92ms/step - loss: 6.7628 - accuracy: 0.0554
Epoch 3/250
89/89 [==============================] - 7s 79ms/step - loss: 6.7418 - accuracy: 0.0554
Epoch 4/250
89/89 [==============================] - 6s 64ms/step - loss: 6.6454 - accuracy: 0.0554
Epoch 5/250
89/89 [==============================] - 4s 47ms/step - loss: 6.5197 - accuracy: 0.0565
Epoch 6/250
89/89 [==============================] - 4s 40ms/step - loss: 6.3964 - accuracy: 0.0627
Epoch 7/250
89/89 [==============================] - 4s 46ms/step - loss: 6.3057 - accuracy: 0.0704
Epoch 8/250
89/89 [==============================] - 3s 37ms/step - loss: 6.2412 - accuracy: 0.0727
Epoch 9/250
89/89 [==============================] - 3s 36ms/step - loss: 6.1849 - accuracy: 0.0745
Epoch 10/250
89/89 [==============================] - 5s 49ms/step - loss: 6.1318 - accuracy: 0.07

In [222]:
accuracy = history.history['accuracy']
accuracy

[0.04829514026641846,
 0.05544916167855263,
 0.05544916167855263,
 0.05544916167855263,
 0.05654978007078171,
 0.06271324306726456,
 0.07035154104232788,
 0.07268484681844711,
 0.07446785271167755,
 0.0772193968296051,
 0.0789143517613411,
 0.08091747760772705,
 0.08197406679391861,
 0.08358097076416016,
 0.08523190021514893,
 0.08562812209129333,
 0.08701489865779877,
 0.08908406645059586,
 0.09038279205560684,
 0.09135133773088455,
 0.09280415624380112,
 0.09434501826763153,
 0.09689845889806747,
 0.09700851887464523,
 0.10050848871469498,
 0.10101477056741714,
 0.10297387093305588,
 0.105483278632164,
 0.10669396072626114,
 0.10885117202997208,
 0.11045807600021362,
 0.11219705641269684,
 0.11435426771640778,
 0.115542933344841,
 0.11701776087284088,
 0.11831649392843246,
 0.11794228106737137,
 0.1210460290312767,
 0.12214664369821548,
 0.12285104393959045,
 0.11144863069057465,
 0.10259965807199478,
 0.11543287336826324,
 0.12042967975139618,
 0.12454599142074585,
 0.12694534659385

### Download Model Object

In [202]:
from pickle import dump,load

In [203]:
# save the model to file
model.save('epochBIG.h5')
# save the tokenizer
dump(tokenizer, open('epochBIG', 'wb'))

## 6. Generating New Text

In [204]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [205]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''

    # Final Output
    output_text = []

    # Intial Seed Sequence
    input_text = seed_text

    # Create num_gen_words
    for i in range(num_gen_words):

        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]

        # Pad sequences to our trained rate (25 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')

        # Predict Class Probabilities for each word
        #pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        predict_x=model.predict(pad_encoded)
        pred_word_ind=np.argmax(predict_x,axis=1)[0]
        #print(pred_word_ind)
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind]

        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word

        output_text.append(pred_word)

    # Make it look like a sentence.
    return ' '.join(output_text)

## 7. Grab a random Text Sequence

In [206]:
print(text_sequences[0])

['etymology', 'supplied', 'by', 'a', 'late', 'consumptive', 'usher', 'to', 'a', 'grammar', 'school', 'the', 'pale', 'usher', 'threadbare', 'in', 'coat', 'heart', 'body', 'and', 'brain', 'i', 'see', 'him', 'now', 'he']


In [207]:
import random
random_pick = random.randint(0,len(text_sequences))

In [208]:
random_seed_text = text_sequences[random_pick]

In [209]:
print(random_seed_text)

['gain', 'the', 'power', 'of', 'enlightening', 'his', 'untutored', 'countrymen', 'for', 'at', 'bottom', 'so', 'he', 'told', 'me', 'he', 'was', 'actuated', 'by', 'a', 'profound', 'desire', 'to', 'learn', 'among', 'the']


In [210]:
seed_text = ' '.join(random_seed_text)
seed_text

'gain the power of enlightening his untutored countrymen for at bottom so he told me he was actuated by a profound desire to learn among the'

In [211]:
model = load_model('epochBIG.h5')

In [212]:
tokenizer = load(open('epochBIG', 'rb'))

In [213]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=3)

1/1 [==============================] - 0s 27ms/step


'christians the arts'

In [214]:
text=' It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find'
print(text)

 It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find


In [215]:
generate_text(model,tokenizer,seq_len,seed_text=text,num_gen_words=3)

1/1 [==============================] - 0s 28ms/step


'myself involuntarily single'

In [216]:
print(read_file('whale2.txt')[250000:251000])

In [217]:
test_text='Three better,more likely sea-officers and men, each in his own different way,could not readily be found, and they were every'
print(test_text)

Three better,more likely sea-officers and men, each in his own different way,could not readily be found, and they were every


In [218]:
generate_text(model,tokenizer,seq_len,seed_text=test_text,num_gen_words=1)

1/1 [==============================] - 0s 28ms/step


'first'

In [219]:
seed_text = "landsman has had fresh fruit to his daily hand and broken the world 's fresh bread to my mouldy crusts away whole oceans away from that"

In [221]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=5)

1/1 [==============================] - 0s 104ms/step


'a way i mean also'